### ISSUE TITLE
amdgpu-pro-rx560 fails to compile with kernel 5.10.3

### ISSUE THREAD

**Issue by hedmo** [boyle/amdgpu-pro-rx560#1]
hi 

and thank you for working on the amdgpu-pro driver for gentoo.i found you hub to day and like to try it 
but it failed to compile . here is the log : 
[amdgpu.log](https://github.com/boyle/amdgpu-pro-rx560/files/5744280/amdgpu.log)

regards hedmo

**Comment by boyle** [comment]
Hi! Glad this might have moved you forward a bit, but the repository was left in a bit of a misleading state after a month long battle with this card. I did get it working in the end and have been using it every day for six months. It has been stable.

I've updated the README with the details of how I got this working. In particular, I ended up using the gentoo 5.6.8 kernel without the amdgpu-pro drivers. This had all the important AMD patches integrated. I *did* use the amdgpu-pro-opencl drivers because the ROCm opencl drivers do not support the RX560.

I have Steam working for any game that works for SteamOS (linux), as well as Blender with OpenCL GPU acceleration. Basically, I won... eventually. Good luck!
